"use strict";
let car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'honda'? I predict False.");
console.log(car == 'honda');
console.log("Is car != 'toyota'? I predict True.");
console.log(car != 'toyota');
console.log("Is car != 'subaru'? I predict False.");
console.log(car != 'subaru');
console.log("Is car.length < 10? I predict True.");
console.log(car.length < 10);
console.log("Is car.length > 6? I predict False.");
console.log(car.length > 6);
console.log("Is car.charAt(0) === 's'? I predict True.");
console.log(car.charAt(0) === 's');
console.log("Is car.charAt(1) === 'u'? I predict True.");
console.log(car.charAt(1) === 'u');
console.log("Is car.indexOf('b') !== -1? I predict True.");
console.log(car.indexOf('b') !== -1);
console.log("Is car.indexOf('x') !== -1? I predict False.");
console.log(car.indexOf('x') !== -1);
